import Navbar from "../components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased `}
      >
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
