import Navbar from "../components/Navbar";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <header>
            <Navbar />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
